ALTER TABLE  `TDM_IM_SUPPLIERS` ADD  `FAVORITE` BOOLEAN NOT NULL DEFAULT FALSE COMMENT  'Избранный поставщик';

ALTER TABLE TDM_PRICES DROP PRIMARY KEY;
ALTER TABLE  `TDM_PRICES` ADD  `PRODUCT_ID` INT( 12 ) NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST ;
ALTER TABLE  `TDM_PRICES` ADD  `PRICE_ORIG` FLOAT( 12, 2 ) NOT NULL ;
ALTER TABLE `TDM_PRICES`  ADD `SUPPLIER_OPTIONS` VARCHAR(128) NULL DEFAULT NULL;
ALTER TABLE  `TDM_PRICES` ADD  `STATIC_MD5` VARCHAR( 32 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE  `TDM_PRICES` ADD  `DYNAMIC_MD5` VARCHAR( 32 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ;