DROP TRIGGER IF EXISTS  `InsertPrice` ;

DELIMITER $$
CREATE TRIGGER `InsertPrice` BEFORE INSERT ON  `TDM_PRICES` 
FOR EACH
ROW BEGIN 
SET NEW.PHID = MD5( CONCAT( NEW.BKEY, NEW.AKEY, NEW.ARTICLE, NEW.ALT_NAME, NEW.BRAND, NEW.PRICE, NEW.TYPE, NEW.CURRENCY, NEW.DAY, NEW.AVAILABLE, NEW.SUPPLIER, NEW.STOCK, NEW.OPTIONS, NEW.CODE, NEW.DATE ) ) ;

SET NEW.STATIC_MD5 = MD5( CONCAT( NEW.BKEY, NEW.AKEY, NEW.ARTICLE, NEW.BRAND, NEW.SUPPLIER, NEW.STOCK, NEW.CODE, NEW.SUPPLIER_OPTIONS ) ) ;

SET NEW.DYNAMIC_MD5 = MD5( CONCAT( NEW.DAY, NEW.PRICE, NEW.AVAILABLE, NEW.CURRENCY ) ) ;

END $$
DELIMITER ;