DROP TRIGGER IF EXISTS  `UpdatePrice` ;
DELIMITER $$
CREATE TRIGGER `UpdatePrice` BEFORE UPDATE ON  `TDM_PRICES` FOR EACH ROW BEGIN SET NEW.PHID = MD5( CONCAT( NEW.BKEY, NEW.AKEY, NEW.ARTICLE, NEW.ALT_NAME, NEW.BRAND, NEW.PRICE, NEW.TYPE, NEW.CURRENCY, NEW.DAY, NEW.AVAILABLE, NEW.SUPPLIER, NEW.STOCK, NEW.OPTIONS, NEW.CODE, NEW.DATE ) ) ;

SET NEW.DYNAMIC_MD5 = MD5( CONCAT( NEW.DAY, NEW.PRICE, NEW.AVAILABLE, NEW.CURRENCY ) ) ;

END $$
DELIMITER ;