DELIMITER $$
CREATE PROCEDURE pricesNullify(IN inBKEY VARCHAR(64), IN inAKEY VARCHAR(64), IN inCODE VARCHAR(32), IN inTIME VARCHAR(10))
BEGIN
	UPDATE 
		TDM_PRICES
	SET 
		AVAILABLE='0',
		DAY='0',
		PRICE='0',
		PRICE_ORIG='0',
		DATE=inTIME 
	WHERE 
		BKEY=inBKEY 
		AND
		AKEY=inAKEY
		AND
		CODE=inCODE;
END $$
DELIMITER ;