CREATE TABLE IF NOT EXISTS `TDM_EMEX_CODES` (
  `BRAND_ID` int(11) DEFAULT NULL,
  `MAKE_LOGO` varchar(32) NOT NULL,
  `MAKE_NAME` varchar(100) NOT NULL,
  PRIMARY KEY (`MAKE_LOGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;