CREATE TABLE `TDM_WS_ANALOG_TIME` (
  `SID` int(9) NOT NULL,
  `WSID` int(3) NOT NULL,
  `PKEY` varchar(64) NOT NULL COMMENT 'md5(ART, AliasGroupId, UserGroupId)',
  `TIME` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE `TDM_WS_ANALOG_TIME`
  ADD PRIMARY KEY (`SID`,`WSID`,`PKEY`);
