CREATE TABLE `TDM_ACTIVE_SEARCH` ( `search_key` VARCHAR(32) NOT NULL , `status` INT NOT NULL , PRIMARY KEY (`search_key`(32))) ENGINE = InnoDB;

ALTER TABLE TDM_PRICES DROP INDEX AKEY;
ALTER TABLE `TDM_PRICES` ADD UNIQUE `STATIC_HASH` (`STATIC_MD5`) USING BTREE;

CREATE TABLE `TDM_WS_ANALOG_TIME2` (
  `WSID` int(3) NOT NULL,
  `BRAND` varchar(64) NOT NULL,
  `AKEY` varchar(64) NOT NULL,
  `TIME` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE `TDM_WS_ANALOG_TIME2`
  ADD PRIMARY KEY (`WSID`,`BRAND`,`AKEY`);

CREATE TABLE `TDM_WS_TIME2` (
  `WSID` int(3) NOT NULL,
  `BRAND` varchar(64) NOT NULL,
  `AKEY` varchar(64) NOT NULL,
  `TIME` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE `TDM_WS_TIME2`
  ADD PRIMARY KEY (`WSID`,`BRAND`,`AKEY`);