DROP PROCEDURE `pricesNullify`;

DELIMITER $$
CREATE PROCEDURE `pricesNullify`(IN `inBKEY` VARCHAR(64) CHARSET utf8mb4, IN `inAKEY` VARCHAR(64) CHARSET utf8mb4, IN `inCODE` VARCHAR(32) CHARSET utf8mb4, IN `inTIME` VARCHAR(10) CHARSET utf8mb4)
BEGIN
	UPDATE 
		TDM_PRICES
	SET 
		AVAILABLE='0',
		DAY='0',
		PRICE='0',
		PRICE_ORIG='0',
		PRICE_SUPP='0',
		DATE=inTIME 
	WHERE 
		BKEY=inBKEY 
		AND
		AKEY=inAKEY
		AND
		CODE=inCODE;
END $$
DELIMITER ;