DROP TABLE IF EXISTS `TDM_ACTIVE_SEARCH`;
CREATE TABLE IF NOT EXISTS `TDM_ACTIVE_SEARCH` (
  `search_key` varchar(32) NOT NULL,
  `status` int(11) NOT NULL,
  `TIME` int(10) NOT NULL,
  PRIMARY KEY (`search_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;